### PR TITLE
#177

### PR DESCRIPTION
**Pull request by devansh289**
Fixed Some Issurs

### CODE REVIEW

**Comment by andreasrosdalw** [comment]
Have you tested that Freeciv-web and Freeciv-proxy are working correctly after these changes? Are you running Freeciv-web with Vagrant?

**Comment by devansh289** [comment]
No, I did not. I'll go do that and fix the issues.

**Comment by andreasrosdal** [comment]
It is very important that you test all the changes. The tests are failing. Lesson learned. Good luck and please try again. 👍

**Comment by devansh289** [comment]
Yeah, will do

**Comment by lonemadmax** [comment]
@devansh289, have you given up on this?

If you are stuck, it may be better to start again and tackle just the easiest parts first. You don't have to solve everything at once.

**Comment by devansh289** [comment]
Hi, school started for me. It's my last year so I really got to focus on that. But, whenever I have free time, I would try working on this.

**Comment by lonemadmax** [comment]
Closing due to inactivity. Please reopen or open a new one if you retake it.

**Pull request closed without merging**
