### PR TITLE
Add contributor guidelines

### PR DESCRIPTION
**Pull request by zekoz**
@mchenryc @lmoureaux @lonemadmax Anything I should add?

### CODE REVIEW

**Comment by andreasrosdalw** [comment]
"- Try not to exceed 200 LOC +- in a single PR."

Remove this!

**Comment by mchenryc** [comment]
> "- Try not to exceed 200 LOC +- in a single PR."
> 
> Remove this!

Agreed - it's pretty arbitrary

+1 for linking the irc/discourse. Some other links might be useful too:

* https://lgtm.com/projects/g/freeciv/freeciv-web/alerts/?mode=list
* http://forum.freeciv.org/f/viewforum.php?f=24
* style guides - With a caveat that these are guidelines of good style, not law.
    * Java - http://google.github.io/styleguide/javaguide.html
    * JS - https://google.github.io/styleguide/jsguide.html
    * Python - https://github.com/google/styleguide/blob/gh-pages/pyguide.md
    * C/C++ https://github.com/freeciv/freeciv/blob/master/doc/CodingStyle#L76

**Comment by lmoureaux** [comment]
> - Try not to exceed 200 LOC +- in a single PR.

- Submit small, self-contained PRs
- Make sure that you update the documentation

**Comment by zekoz** [comment]
I don't state it as an absolute, it's a recommendation. 200 cloc changed will take 15-30 minutes for me or someone else to to properly review. That's not arbitrary, that's about the amount of time I have to review PRs for a side project. If you think you need 1000 cloc in a single PR, then the reviewer will understand that or tell you to split it up.

**Comment by zekoz** [comment]
> * https://lgtm.com/projects/g/freeciv/freeciv-web/alerts/?mode=list

Is there a way to use this as a linter for a PR rather than a suggester of random style changes to make?

**Comment by zekoz** [comment]
lgtm.com pull request integration:

>Not admin / owner of repository
>You must be an admin or the owner of a repository to configure continuous integration.
If you are an admin or owner, make sure you connect the appropriate external accounts on your account settings page.

>OAuth token revoked.
>Please try deactivating and reactivating the pull request integration. If the problem persists, please report the issue.

@jtn20 Could an admin/owner reactivate lgtm.com presubmits here?

**Comment by lonemadmax** [comment]
Is this only blocked on the 200loc line? I find the "Try" it starts with enough to understand that it's a hint. If that's just me, lmoureaux's suggestion is good.

**Comment by lonemadmax** [comment]
Administrative silence. With no hard rejections, I'm committing this as a good starting point. For the nice additions commented in this thread, please submit small, self-contained PRs :-)

**Pull request merged**
