### PR TITLE
Clean up install/provision output

### PR DESCRIPTION
**Pull request by mchenryc**
Still a lot of noise, but this removes the 'progress updates' of some commands, and unnecessary extraction logging.

apt-get change from: https://stackoverflow.com/a/25907959/80714

### CODE REVIEW

**Comment by lonemadmax** [comment]
Any reason to make freeciv/freeciv-web.project executable?

I'll miss the colors in mvn output when rebuilding, but I'll trade them to getting rid of the progress messages during install.

**Comment by mchenryc** [comment]
> I'll miss the colors...

When we can upgrade to maven to to 3.5.3, colors "should" be available, according to: https://issues.apache.org/jira/browse/MNG-6296

**Review by lonemadmax — CHANGES_REQUESTED** [review]
When possible, please revert the change in  freeciv/freeciv-web.project permissions.

You may also want to change the comment: the SO link is for the mvn change. But the apt-get one is easy to find now that you did the work and we can directly search the change.

**Comment by mchenryc** [comment]
Thanks for the pr-proofreading - All addressed.

**Comment by mchenryc** [comment]
@lonemadmax FWIW, you're notice of the execution bit flip prompted me to find [this](https://stackoverflow.com/a/1580644/80714), which solves something that has plagued me for years:

    git config --global core.fileMode false

Perhaps not "recommended" but I find it immediately useful.

**Pull request merged**
