### PR TITLE
WIP: Run Freeciv Web in docker containers

### PR DESCRIPTION
**Pull request by jacobrask**
I think it's a good idea to be able to run the different projects in isolation in separate containers with their own explicit dependencies.

I am having troubles running the development environment on my laptop due to the system requirements. Transitioning the different parts to Docker containers would at least

1. Remove the Vagrant and Virtualbox intermediary step. They require more resources than just Docker, especially at boot/suspend.
2. Let you install and run only what you need for a particular task. Firefox is needed for testing, but not for running the web server, and possibly other parts of the system could be disabled when they are not needed.

So far this works:

- [x] freeciv-server
- [x] freeciv-proxy
- [ ] freeciv-earth
- [ ] freeciv-web
- [ ] freeciv-publite
- [ ] testing

Run `docker-compose up -d`

And you should now be able to connect to the Freeciv Proxy on port 8002. You will need to add the `host: 'freecivserver'` property to the initial web socket message to tell the Proxy to connect to the `freecivserver` container.

Help converting the other projects would be welcome.

### CODE REVIEW

**Comment by andreasrosdal** [comment]
It would be very useful to have Freeciv-web running on Docker, so thanks a lot for working on this! 
I hope that you will complete this very nice improvement.

I can't merge this pull-request until the Travis CI tests passes without any errors, see:
https://travis-ci.org/freeciv/freeciv-web/builds/239671669?utm_source=github_status&utm_medium=notification

I think the problem is related to the changes in Freeciv-proxy. 
Have you considered the security effects of the change to Freeciv-proxy?

Thanks again!

**Comment by ghost** [comment]
It would be very useful to have Freeciv-web running on Docker, so thanks a lot for working on this! 
I hope that you will complete this very nice improvement.

I can't merge this pull-request until the Travis CI tests passes without any errors, see:
https://travis-ci.org/freeciv/freeciv-web/builds/239671669?utm_source=github_status&utm_medium=notification

I think the problem is related to the changes in Freeciv-proxy. 
Have you considered the security effects of the change to Freeciv-proxy?

Thanks again!

**Comment by jacobrask** [comment]
I think you should wait merging it anyway until it's all done, but I wanted to push it up to get feedback.

Not sure what the security implications could be, you could connect to an arbitrary Freeciv Server but do you think that could be a problem? I am learning as I go here :)

**Comment by ghost** [comment]
> I think you should wait merging it anyway until it's all done, but I wanted to push it up to get feedback.

I think this will be great once completed!

> Not sure what the security implications could be, you could connect to an arbitrary Freeciv Server but do you think that could be a problem? I am learning as I go here :)

I'm thinking it would be safer to specify the civserverhost value using a command-line parameter to Freeciv-proxy, rather than having the civserverhost value set by a field in the login message. That way the production Freeciv-proxy will never be able to connect to a different host than 127.0.0.1.

**Comment by ghost** [comment]
> I am having troubles running the development environment on my laptop due to the system requirements. 

Please report these as bugs also, perhaps it is something which can be fixed.

**Comment by ghost** [comment]
Any news on this?

**Comment by ghost** [comment]
Please reopen this pull-request once it is ready. Closing.

**Pull request closed without merging**
