### PR TITLE
Update list of known servers

### PR DESCRIPTION
**Pull request by andreasrosdalw**
- Freecivweb.org currently has a [cease and desist issue](https://github.com/Lexxie9952/fcw.org-server/issues/168) because of an AGPL license violation. Freecivweb.org is currently not publishing the source code in compliance with the AGPL license. The source code of the version running on the live server is published on a private server. Therefore Freecivweb.org will be removed from the list of known servers.

### CODE REVIEW

**Comment by Lexxie9952** [comment]
1. As an experiment I sent a neutral party with the mission of "can you visit their site point me to their AGPL source code or how to get it?"  I received a link to a repository that was withholding source code on production and was not AGPL compliant.
2. A zip file is deliberately defiant of open source collaboration for a variety of reasons, some of which are (but are not limited to:)
a. doesn't allow you to see what was changed, which means looking for needles in a haystack and is extremely obstructive of viewing component interactions between separate parts of the project
b. doesn't give accreditation
c. doesn't give commit history or commit comments
d. doesn't give a way to selectively integrate, pull, push, etc.
e. does not auto-unpack into an installable functioning server that can be tested
f. is not a real-time accurate snapshot of the state of the server or cannot be known to be such without inordinate amount of investigative work, which i resent having to do the first time to discover the non-compliance of this licensee
g. is not obvious or prominent or discoverable to the users of the project

IN SHORT, a licensee making cease and desist orders on its licensor while executing a great deal more deliberate effort to OBSTRUCT access to their content while simultaneously trying fool the public into their claims of compliance (while being non-compliant), simultaneously making FALSE cease and desist claims against the licensor, and simultaneously executing a public propaganda campaign against its licensors that goes so far as to slander me personally by finding the most annoying person in the community and claiming it's really an 'alt identity' of me, is viewed by this repository as toxically against all open source collaboration and makes us make a rare exception to our normal policies and indeed insist on every single right we have to resist motives clearly hostile to the furtherance of this project and its community.

Please immediately make your site 1) AGPL compliant per the standards above, then we will consider changing our current stance that the above requests are not in earnest and are done in bad faith.

**Comment by andreasrosdalw** [comment]
Freeciv-web is open source and released with the AGPL license, the original [Freeciv-web license is here](https://github.com/freeciv/freeciv-web/blob/develop/LICENSE.txt).

The website at [freecivweb.org](https://www.freecivweb.org) is currently violating the AGPL, by not publishing the license in accordance with the AGPL license. The source code for development of freecivweb.org was moved from the GitHub repo, and is currently in a private git repository. 

I suggest that the source code is published in accordance with the AGPL license. 

I support the Cease and Desist described in this issue: https://github.com/Lexxie9952/fcw.org-server/issues/168 

Can you please merge this pull request? @kvilhaugsvik @cazfi

**Comment by cazfi** [comment]
Leaving aside the question of that particular cease and desist (whether the freecivweb.org source is available for a *particular* user) to keep task of reviewing this commit manageable, I note that freecivweb.org currently does this to me, and presumably *everyone*: "Development" link points to https://github.com/Lexxie9952/fcw.org-server , which claims that it's "The current state of the https://www.freecivweb.org server." Nowhere obvious does freecivweb.org mention that the source code is actually in some private repository, nor does it provide means or instructions how to access it.
As for the TnT site, it has never even been part of this list of compliant sites.

I'm not merging the commit immediately, instead preferring that full time of review period will be given to Lexxie for making freecivweb.org AGPL compliant, or at least to publish an acceptable plan towards that goal.

**Comment by cazfi** [comment]
> preferring that full time of review period will be given to Lexxie for making freecivweb.org AGPL compliant, or at least to publish an acceptable plan towards that goal.

Sorry for not clarifying this earlier (I have rather limited time to work on the matter): Review period for freeciv-web pull requests is 72h (3 days). Andreas did the pull request 3.10 18:36 UTC. That gives him the right to merge it after 18:36 UTC tonight.

**Comment by andreasrosdalw** [comment]
@cazfi Can you please give me commit access to this git repository again? At some time on the past, I decided to retire from Freeciv-web development. Now I would like to make some commits again.

**Comment by cazfi** [comment]
There has been some development on the matter, but I've not looked closely at it. @andreasrosdal can you re-evaluate freecivweb.org compliance now?

**Comment by cazfi** [comment]
> I note that freecivweb.org currently does this to me, and presumably _everyone_: "Development" link points to https://github.com/Lexxie9952/fcw.org-server , which claims that it's "The current state of the https://www.freecivweb.org server." Nowhere obvious does freecivweb.org mention that the source code is actually in some private repository, nor does it provide means or instructions how to access it.

At least these misleading links and documentation are still in place (7th Oct 2021 19:04 UTC). They in themselves make the site not compliant.
Apparently the only development there has been is that they gave source code to the one party that had the Cease and Desist issue opened. There's no mention about even plans to fix the issues in general.

**Comment by cazfi** [comment]
> @cazfi Can you please give me commit access to this git repository again?

Wasn't as easy as it should - seem have an issue with my own github account. Maybe I have time to resolve it during weekend, in a controlled manner.

**Comment by lmoureaux** [comment]
> Apparently the only development there has been is that they gave source code to the one party that had the Cease and Desist issue opened. There's no mention about even plans to fix the issues in general.

I haven't received anything so far and the C&D issue was locked.

**Comment by Lexxie9952** [comment]
This is a non-issue to waste no more time on. Briefly,

1. The C&D was been declared and judged to be (under normative qualifiers for such), malfeasant, erroneous in claims, and not made under accurate intellectual property counsel (or indeed any counsel at all.) However, that is a moot point at this stage.
2. Andreas R. pre-approved this plan so it makes no sense for him to be doing such a PR.
--
Current plan / state of situation:

1. AGPL violators and their agents, collaborators, colluders, and representatives are now compliant, which was the condition FCW made for source release, under advisement.
2. FCW will publicly expose all required content to the general public on a Github branch.
3. Step (4) requires technical know-how in how to clone branch from repo A to a new branch in repo B. Consulting with Andreas R., he said he didn't know how to do it. Resolution will be done with reasonable expeditiousness upon discovery of the proper technical steps to execute it.

**Comment by lmoureaux** [comment]
```
git remote add B git://repo-b-url
git push B branch-name
```

**Comment by Canik05** [comment]
> 
> 
> This is a non-issue to waste no more time on. Briefly,
> 
>     1. The C&D was been declared and judged to be (under normative qualifiers for such), malfeasant, erroneous in claims, and not made under accurate intellectual property counsel (or indeed any counsel at all.) However, that is a moot point at this stage.
> 
>     2. Andreas R. pre-approved this plan so it makes no sense for him to be doing such a PR.
>        --
>        Current plan / state of situation:
> 
>     3. AGPL violators and their agents, collaborators, colluders, and representatives are now compliant, which was the condition FCW made for source release, under advisement.
> 
>     4. FCW will publicly expose all required content to the general public on a Github branch.
> 
>     5. Step (4) requires technical know-how in how to clone branch from repo A to a new branch in repo B. Consulting with Andreas R., he said he didn't know how to do it. Resolution will be done with reasonable expeditiousness upon discovery of the proper technical steps to execute it.

A possible solution might be to simply remove and replace the config folder in your private repo with a generic one that doesn't contain server secrets then make your private repo into a public one. Either that or Louis' suggestion should work. With years of Administration experience under your belt I'm sure you can figure it out very quickly. Just please release the full code as you build it on freecivweb.org. Thank you. I look forward to getting past all this and future collaboration.

**Comment by andreasrosdalw** [comment]
Freecivweb.org is currently still violating the AGPL, in the following two ways:

- Not publishing the source code of Freeciv-web in accordance with the AGPL. Freecivweb.org is currently not an open source project which publishes the source code in accordance with the AGPL license. The source code of Freecivweb.org  is still in a private Git repository.
- Imposing additional license requirements which go beyond the AGPL, as described here:  https://github.com/Lexxie9952/fcw.org-server#about-fcw-and-this-repository - these additional license requirements are in violation of the AGPL license.

I have not pre-approved these actions by Freecivweb.org.  

Freeciv-web has the AGPL license, which may be found here: https://github.com/freeciv/freeciv-web/blob/develop/LICENSE.txt

**Comment by cazfi** [comment]
>     * Imposing additional license requirements which go beyond the AGPL, as described here:  https://github.com/Lexxie9952/fcw.org-server#about-fcw-and-this-repository - these additional license requirements are in violation of the AGPL license.

Yes, that's quite terrible. It reads like something one could do to restrict who might *become* their licensee, but of course there it's imposed on those who already are licensees, and thus already have all the rights given by AGPL, after visiting their public site.

**Comment by cazfi** [comment]
In https://github.com/Lexxie9952/fcw.org-server/issues/168#issuecomment-937119722 has promised the source code within 48h from 6th Oct 2021, 10:56 UTC.

The time (23:56 UTC+3 tonight) is not ideal for me to check the situation, but as it's mere hours after I could be merging this pull request otherwise, I'm inclined to give them that additional time.

**Comment by M-i-k-o-t-o** [comment]
Has there been any update regarding this?

**Comment by Lexxie9952** [comment]
"Yes, that's quite terrible. It reads like something one could do to restrict who might become their licensee, but of course there it's imposed on those who already are licensees, and thus already have all the rights given by AGPL, after visiting their public site."

I'm saddened you have misunderstood it. FCW does not, nor cannot, impose any alterations to the AGPL.

Similarly, the AGPL does not, nor cannot, restrict rights of private communities to have repository policies for accepting PRs, or Terms of Service to use their website.  I hope this clears that up.

**Comment by kvilhaugsvik** [comment]
> Has there been any update regarding this?

https://github.com/Lexxie9952/fcw.org-server/commits/dev

**Comment by lmoureaux** [comment]
Probably depends how you interpret the new sections in `README.md`. I guess one could argue that the "voluntary mutual relationship" starts when anyone points his browser to the fcw website and the server accepts to serve files to the user. This would meet the requirements of the AGPL (even if then the text says just... nothing). Also, the new sections mention Terms of Service that don't seem to exist (or at least are not clearly identified as such nor linked from anywhere I looked), most of the added text and "agreement" is probably void anyway.

Unnecessary encumbering redistribution with legal-looking text isn't in the spirit of open source, but one can probably get away with it. The most important part is that now we have the source, even if not properly linked from the website (which still points to the `master` branch). Let's hope that the new branch will keep being updated...

I would still urge anyone to avoid contributing to fcw because of the CLA part.

**Comment by cazfi** [comment]
On Fri, 22 Oct 2021 at 23:35, Lexxie9952 ***@***.***> wrote:

> "Yes, that's quite terrible. It reads like something one could do to
> restrict who might become their licensee, but of course there it's imposed
> on those who already are licensees, and thus already have all the rights
> given by AGPL, after visiting their public site."
>
> I'm saddened you have misunderstood it. FCW does not, nor cannot, impose
> any alterations to the AGPL.
>
> Similarly, the AGPL does not, nor cannot, restrict rights of private
> communities to have repository policies for accepting PRs, or Terms of
> Service to use their website. I hope this clears that up.
>

 Obviously the problematic part is not that you're not accepting all
contributions. The main problem is in "... nor release source code...". At
best that section means absolutely nothing, and exist only to mislead
people to think they don't have the rights they do. As far as I know
freecivweb.org is completely public (no limitations to who may enter the
site and thus is your user). So any talk about "non-users" means...
nobody... nobody is excluded from having the right to the source code etc.


 - ML

**Comment by M-i-k-o-t-o** [comment]
It looks like https://github.com/Lexxie9952/fcw.org-server/issues/168 was censored by @Lexxie9952, this removed any faith of goodwill that I had in them. Thankfully there is an incomplete archive of that issue here https://web.archive.org/web/20211003142831/https://github.com/Lexxie9952/fcw.org-server/issues/168

I have to say that I am more than disappointed.

**Comment by lmoureaux** [comment]
It was interesting to see the steps taken by Lexxie...

1. Reply to me
2. Respond to comments by Canik and cazfi
2. Delete said comments, leaving the answers
3. Edit out the answers
4. More discussion with me
4. Close the issue
5. (I reply saying that it's not over from my point of view until the source is published)
5. Lock comments
6. (Source published)
5. Delete the issue

**Comment by Lexxie9952** [comment]
Mikoto, you should be more aware of underlying incidents before judging. As people will see by reading the below, it's an exhausting lot of drama these people have created, so you'll forgive me if I haven't had the energy for full public disclosure earlier. Other private entities can vouch for it though.

It appears all facts of the case should be made apparent now to protect against future misunderstandings and misinformed actions or decisions coming from those misunderstandings. 

This issue was part of a hostile political campaign where AGPL violators and individuals assisting them, were doing live production releases and competitively imply credit for our features before we had a chance to release on our own server. In itself, since everything is eventually free and open anyway, this is only a minor annoyance. But it becomes a lot more annoying when the same parties then add their own features that are closed source, not published, and clearly violating AGPL.  Still not annoying enough? How about, then poaching of your users and donors, against your ToS. Still not enough? Openly advertising their superiority in features (that they took from you before you released to production), and implying their features are theirs. Not enough yet? Not crediting you, and implying to themselves a huge amount of credit for your own work. Not enough? Complaining that you don't credit them enough, in public. Some of this is subjectively infuriating and some of it is objectively pernicious. I let you know all of it, as some people are more concerned with objective facts and others like to understand the human side of what's going on, for a better context.
  
Whether the human ethical side or the objective factual side is more important to you, one thing is sure. This was a CLEAR CASE of what is known as the "Parasite Model" ... where a bad actor tries to out-compete a compliant site by taking everything they do, to be instantly equal to them, then add some extra features that are proprietary and closed source, such that you cannot compete with them. The model is rigged against positive good compliant people, and stacked in favour of cheaters. No matter how hard you try and how many more features you produce over them, you'll always be behind when a parasite model chooses to compete with you.

Clearly, Parasite Models not only violate AGPL, but are an abomination of the culture that open source collaborative projects require in order to thrive. This is how the incident began. Why did the instigators of the incident not want you to know this part? Hmmm, very interesting.

This made us decide the time was right to finally implement advice we had for a long time. THAT IS, to change our repository structure and workflow.  A single repository for development, testing, release, and public publishing just couldn't do the job anymore. The main reason for doing this is that it will eventually allow better upstream integration of our features when we get the workflow to where we can package features in single commits (instead of dozens commits during development, beta-test, and bug-fix.) But yes, indeed, I admit another reason was also to avoid cases where someone releases your code on their non-compliant violating server before you do, while making statements that their site has everything your site has plus more hidden features yours doesn't, implying your features are theirs, and without crediting you that most of those features came from your own repo before you rebuilt it on your live production server. In my opinion, it would be especially evil if you also claimed that when the original creator releases their own feature after you "pre-released" it first, if you implied in competitive advertising that they're "copying"" you.
 
Who here does not think this egregious? Who here thinks it's totally fine that the hours of talk spent over this incident has not spent a single minute admonishing the people responsible for this? Don't have time to investigate repos, forum posts, and timestamps? Fine, at least admonish that in principle anyone who did do these things would be violating the open source culture we all depend on to make the project thrive. Who here thinks any of this incident would have happened at all, if not for this as the true original wrong-doing of the parties that instigated it all? These are not rhetorical questions --- please answer if you do not think such behaviour is egregious.

**I _pre-emptively_ made upstream aware of this on an ongoing basis.** Indeed, and this is the important part ....

BEFORE any actions I took, I was careful to document and notify upstream of it. I gave all the reasons, I listened to suggestions, advice, and so on. I informed Andreas what's going on and have chat logs of his answers and concerns and approving statements like "Excellent plan!"  I asked questions and gave opportunity to advise me on any matter whatsoever. All of this before going on vacation, and then continued after I got back.

It is notable that no upstream maintainer took any action, commenced any discussion, or made any statements to the original instigators during this period (that I am aware of.)  I do not fault them for it, I know exactly what it's like to not have time to do focus on every possible thing with quick perfection. My point still stands though, that if you do dedicate any time to it, it should not reward the wrong-doers with the exact outcomes they try to orchestrate and manipulate. **_When you reward wrong-doing with the outcome it desired, it only encourages a continuance of this model of intra-community political warfare._**   

Anyway, at this point I had acquired the "implied suggestion" that we should have a private dev repo, then publish to public repo after the changes go up on live production server, and a master repo that is features packaged into isolated clean commits. Getting to where we are able to do this is what I refer to as "repo/workflow migration."

So yeah, this was the context in which the repo/workflow changes began to be set up. AND private disclosure to upstream that I'm doing it, and the state of the situation with the bad actors above. Meaning plenty of opportunity to go check things out.  This next part is also important.....

BEFORE doing it, I made prophecies and predictions about what might happen when someone violating the AGPL under the "parasite model" lost their free bloodsucking host organism. I predicted that known enemies who care nothing about the source in question would capitalize on it. Then it happened just like predicted. What better proof is there? Well there's lots, but this at least counts for something. The point is that it's true, FCW is continually harassed and watched like a hawk for vulnerabilities such as this, then pounced on in political attacks meant to degrade us. And here is what almost no one knows. They do not like our vision of client agnostic server with both web and native uniformly and universally accessing a single compatible server. I don't know why, I never ask. But every single thing around this issue always gets sabotaged, and recently upstream started making big strides in progressing toward this goal. 

I am convinced about the causes for what ENCOURAGES, ENABLES, and EMPOWERS the political warfare from bad actors.
It is that there are never any warning statements or disciplinary actions ever imposed on the people who start it. They always get away with it and are usually REWARDED for it in seeing the outcome they desire (which is, to degrade the battle target's userbase, reputation with upstream, reputation within the community, etc.) If there are never any third party mediations, inquests, or anything; never any moderation; never a code of conduct about defaming other platforms or operators; an anarchic 'wild west' atmosphere, then you get exactly like the wild west cowboy movies had. Outlaws, villains, stage-coach robbers, all of it.

Most people do casual speed reading of dramas to make a quick opinion. Who wants to dig deep in someone else's shit? I don't blame anyone for not wanting to. But be warned. This is their ART FORM. What am I talking about? The ART of making casual first appearances deceive you, to manipulate you into a false judgment that is the desired outcome of their abusive and unethical war campaign. I want to be clear how important this is. It is their ART FORM. They are artists at making impatient speed-readers who glance over a few facts, come away with bad impressions meant to tarnish the target victim of their battle tactics. Every true wrong-doing or fact of what's going on is carefully camouflaged and premeditated to be hidden out of sight, omitted, undisclosed, with carefully prepared denials. Countless times, every time I try to show what's really going on, it gets dismissed as a long story with the claim that 'the truth is so simple, we're only trying to do something reasonable here...' Everything is hidden or distracted under their carefully managed "he-said she-said" claims that are difficult to untangle and extremely frustrating to the patience of someone just trying to make a casual judgment. But this next part is important.... they know everything here fully, are aware of it and more, and are motivated to artfully try to CONTROL a narrative to harm other members of the Freeciv community. And that is a terrible transgression that needs correcting.
 
After becoming aware of the migration in our repo/workflow policy, they waited for my vacation to make source code requests on beta code, _while their own affiliated site was still in the parasite model of violation of the AGPL._ (Later, they pointed out they had some dated .zip file containing absolutely no commit history, which was not advertised on the site, and which investigation of minified web source revealed was not true state of the server, and for multiple other reasons was clearly a violation of AGPL.)

Lmoureaux has historically been involved in fork vs fork propaganda vs. FCW, and is a chief contributor of another site that is in one-way open warfare against us, continually ignoring our requests to leave us in peace. It may appear to casual observers that we are also in warfare with them. Absolutely NOT. Everything we ever say or accuse is always a defensive response to a campaign they start. This is VERY important for people to verify and indeed CAN be verified by investigating all archive histories you have access to.  Months go by in quiet, then a new instigated attack comes for which we must defend ourselves. The site and the collusive group affiliated with it have been involved in both technical and political campaigns against FCW, almost non-stop for the last several years.

Lmoureaux started assisting the "parasite violator site" and acted as their agent in making source code requests for them, claiming to be a third party making independent requests. As the history in your archive shows, he was asked for non-hypocrisy or "symmetry" -- (i.e., don't make requests to one site on behalf of another site until the site you assist/affiliate with is first compliant). _For those unfamiliar with common law, anyone violating a contract or license abjures the right to enforce it on someone else._ So here we have an agent of a parasite instance that is not AGPL compliant, taking advantage of timing and repo workflow migration, to politically publicize against a site they do not deny to be enemies of, during a time when they know we're technically unable to comply. OK, sounds bad, maybe there's a different side to it and it's just a misunderstanding, right? No. There is additional context you need to know. There was also:
1. an aggressively hostile non-collaborative attitude
2. multiple and diverse legal threats being made by them
3. legal threats being made to our domain holder
4. extortion/blackmail to our domain holder to shut down the site
4. threats to dox people
5. threats of copyright claim enforcement
6. false political propaganda in discord, slander campaigns

In the public forum is just "We are so reasonable and just asking reasonable request, when is it coming?" Even though privately they already know everything I said above. Pure politics with a very specific goal... to fool YOU, the reader, into having a bad image of us. 

Within this context, Lmoureaux made claims about our license obligations which my expert advice informed me was not only false, but ridiculously false and "a real stretch of the imagination." Whatever people privately think about whether those claims be true or not, the entire point was moot. That is, FCW is an open source GPL/AGPL project which has always published its code, and they knew we were were stuck in a migration of our repo/workflow process and on vacation, and knew they had been informed privately on repeated occasions that our beta test would be released, live, and public within 90 days. The hope was that we couldn't do it within 30 days so they could (in their mind), enforce certain clauses to shut down our site. All of this took place in the context of them knowing they were making the request on behalf of a non-compliant AGPL violating "parasite instance." The true state of things is actually a lot more detailed and worse than what I state here, and also I'm sure there will be excuses, denials, and half-truths that try to seem simpler and more reasonable, such that I am the one making up some fantasy... I say this because it is their typical modus operandi, to always have the plausible deniability strategy and "we're just nice reasonable people." If what I'm saying is even half true, nice reasonable people don't get involved in stuff like this.

I notified upstream of the plans for workflow/repo migration long before any of this happened, and indeed, am grateful for their help in doing it.  This job was challenging to me. and I'd like to thank upstream for spending HOURS to get to where we now are at.

The point is that whether or not any of their claims are true, they knew we couldn't do it anyway.  I was advised that the hostile party's claims about our licensing obligations were FALSE. We resisted not only because we didn't have the time or technical resources to immediately comply, but because the nature of the request was obviously malicious and apparently trying to leverage false interpretations of license obligations. I had to make a decision about bending over to their plans for destroying FCW through support of the parasite model, or putting up a fight. I put up a fight. An ugly fight and in retrospect, you can watch the video of a fight and think where you could have better ducked, dodged, or punched.  Yeah, not a perfect fight. But a righteous and saintly fight justified by every ethical and cultural norm of the open source community.

The "Op42/Cobra" coalition then did their usual modus operandi of opening up a full political propaganda campaign to try to tarnish FCW. Evidence of the hostile motives are all over the place, especially on Discord, if you want to know the true character of these people, go look for yourselves. Consider that Lmoureaux omits in his history all facts regarding the beta-test, repo migration, vacation, the former AGPL violation status of TnT, the pre-release "credit-thefting", and his own relationship acting as agent of the violating site. Ask yourself, what is motivating wieder for HOURS EVERY DAY to be making false and degrading statements about FCW, instead of just collaborating or going to work on some project to make things better for his site or the whole community?  

Two weeks ago (ish), they pulled the "Red Hat" trick. Finally doing a release to become compliant (i.e., bundle every single change in a single commit that makes it impossible for anyone to review or integrate). Admittedly this did make them finally compliant. FCW won't stoop to such tricks and it took us a little longer to get our workflow figured out, but we recently did such.  Therefore this issue should be officially over, right? The drama-instigators and the FCW site are now both inarguably compliant. Well, no, not if the real motive behind this has nothing to do with source code and has a different agenda. In cases like that, you'd see people involved in it posting things to make us look bad, and possibly a few innocent bystanders fooled by them and making judgmental statements against us, out of context or full knowledge of the issue. Have we been perfect? No. But please don't make statements that completely IGNORE the context under which all this is happening, without even a single statement like "understandably this is a hard situation for you to be in" or something like that to show there is no bias.
 
Finally then, to answer the original question about the issue being closed by deletion:

The incident is harmful to the collaborative atmosphere of the community. It is rife with mistruth and is clearly the kind of 'propaganda war' this community needs leadership and policies to absolutely ELIMINATE. In this context, FCW wisely accepted advice to close the incident via deletion. Anyone interested in viewing the hypocritical asymmetry of it, by comparing timestamps of what happened at which points in the history of it, can indeed refer to the web archive you have posted, and you are encouraged to do so. Be careful in future to not be a manipulated instrument of wrong-doers who are calculating to fool you into their own evil outcome, which is to sow dissension and discord and zero-sum games into the community.
 
For now, the greater Freeciv project clearly needs some direction to discourage such dishonest campaigns from happening again. Specifically, creating such complex dramas and situations in an artful way where casual observers will come away feeling someone has a tarnished reputation. No one wins by making upstream maintainers disgusted with their community. Everyone wins by spending a lot more time brainstorming new ideas, coding them, and figuring out how to integrate them. Do not be mistaken, the correction to preventing future occurrences has nothing to do with licensing. That issue is now over with. The next campaign will be maliciously started over some other opportunistic vulnerability.

Best Regards

**Pull request merged**
