### PR TITLE
More build system

### PR DESCRIPTION
**Pull request by kvilhaugsvik**

### CODE REVIEW

**Comment by andreasrosdalw** [comment]
I'm not sure about this one. Can you add more information about why?

**Comment by kvilhaugsvik** [comment]
> I'm not sure about this one. Can you add more information about why?

I'm assuming you are asking about the removal of apt-get upgrade: Installing upgrades can cause issues. Stuff we depend on that needs an upgrade will be upgraded as a part of installing our dependencies. The problem that caused me to remove it is that running an upgrade on Ubuntu focal on Travis sometimes will lock up the build.

**Comment by kvilhaugsvik** [comment]
(Removal of the upgrade isn't enough to make building on Ubuntu focal work)

**Comment by kvilhaugsvik** [comment]
Example: https://travis-ci.org/github/kvilhaugsvik/freeciv-web/builds/706530809

**Pull request merged**
