### PR TITLE
Frontpage & Game List facelift

### PR DESCRIPTION
**Pull request by adaxi**
Big one incoming!

This pull request attempts to incorporate ideas from issue #61.

- The metaserver servlet is not resposible to display the games list, a dedicated servlet is now used for that purpose.
- All the head/header/footer are now included in all the pages through JSP includes. 
- When possible update the servlet output to JSON instead of CSV.
- It was tested for mobiles and tablets.
- meta directory does not exist anymore.
- chinese translations where incorporated into the new design: parts where no translations were not available were hidden.

Important notes for deployment:
- The database is now created using flyway, instead of by importing the dump.
- nginx configuration was updated, the language selection is now done by the servlets. (take care to remove references to $lang.
- Please review/test the changes before going to production.

### CODE REVIEW

**Comment by ghost** [comment]
Very nice! This will be a good improvement!


Why is the database initialized with Flyway? How can I release this to production then?

The tests fail on the Travis CI build: https://travis-ci.org/freeciv/freeciv-web

**Comment by adaxi** [comment]
It does not even reach the tests in Travis :-(, it fails do build the WAR. I'll have a look at this during the week.

Regarding the database, it will not impact production since the schema was not altered.
I suppose that to put it in production is:

1. Update the nginx configuration so that it does not take into account the language settings.
2. Update the ROOT.war.

Regarding the database:
Instead of doing:
```sh
mysql -u ${mysql_user} -p${mysql_pass} freeciv_web < ${basedir}/freeciv-web/src/main/webapp/meta/private/metaserver.sql
sudo -u ubuntu mvn compile flyway:migrate
```

Now you only need to do:
```sh
sudo -u ubuntu mvn compile flyway:migrate
```

You can see the changes in the travis and vagrant build scripts.

**Comment by adaxi** [comment]
I almost forgot, I also improved the format of /mailstatus to return JSON format instead of a mix of html and json. The pbem process will need to be restarted. I could not easily test pbem game list in my test environment, i ended up mocking the request to /mailstatus it with a static file.

**Comment by ghost** [comment]
This is a great improvement, thanks a lot!

**Comment by adaxi** [comment]
If there is any issue that you detect during testing, just report it here I will try to fix it.

**Comment by ghost** [comment]
This has been released to production now. I like it very much. 

More pull-requests to Freeciv-web welcome! What do you think we could improve in the actual game to make it better for the average player?

**Comment by adaxi** [comment]
From what I seen in the reviews user seem to be complaining about bugs:
https://chrome.google.com/webstore/detail/freeciv/ldhdjhmbapbeafmhdoobnlldhfopfcgh/reviews

I suppose next step will be to play a lot, and attempt to fix all encountered bugs.

- When starting a WebGL game, the textures take a long time to download, and you don't know if it is working. Perhaps a progress bar indicating the progress would be helpful.
- We need to fix this issue of resources not downloading: http://imgur.com/a/8usWL, I could not start a game just now.
- This weekend I showed the WebGL version to my brother, and we tried to play without creating an account, but it was not possible, we ended up creating an account.
- When on the WebGL 3D view, it is not clear that an unit is active, perhaps the ring around the unit should have some animation, or something similar.

**Comment by adaxi** [comment]
Also it seems we have a bug in the play by email finished games: https://play.freeciv.org/game/list?v=play-by-email, they have all 122 and 16 wins respectively.

**Comment by ghost** [comment]
Yes, fixing bugs such as these would improve the game a lot.

**Pull request merged**
