### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [LGTM code quality badges](https://lgtm.com/projects/g/freeciv/freeciv-web/ci/#badges) to your project, to show how you care about code quality and encourage contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/freeciv/freeciv-web).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by andreasrosdalw** [comment]
Thanks! I have another suggestion: 

Please let me use lgtm.com code review on this project:
https://github.com/LibrePDF/OpenPDF
it's not the root project, but it is the maintained fork.

**Comment by xcorail** [comment]
Hi @andreasrosdal 

Certainly! Just click on [My Projects](https://lgtm.com/dashboard) at the top right of lgtm.com, and add your project

Let me know how it goes.

Cheers

**Comment by andreasrosdalw** [comment]
@xcorail  I get this error: "This project appears to be a fork of ymasory/iText-4.2.0. Currently we do not support analysis of forks. Consider adding ymasory/iText-4.2.0 instead."

**Comment by xcorail** [comment]
Sorry @andreasrosdal my bad I didn't read your comment entirely :(
(I saw you posted a message on our community forum, we'll answer you there)

**Pull request merged**
