### PR TITLE
packhand.js: Declare map as global

### PR DESCRIPTION
**Pull request by cazfi**

### CODE REVIEW

**Comment by andreasrosdalw** [comment]
map is already declared here:  https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/javascript/map.js#L21
So this looks like a mistake.

**Comment by cazfi** [comment]
That declaration is not visible on packhand.js.

**Comment by andreasrosdalw** [comment]
All the JavaScript files are bundled together by Closure compiler when the project is built using Maven. So there is no concept of variable scope or variable visibility in specific JavaScript files. Closure compiler will bundle and minify the JavaScript files into one file.

**Comment by cazfi** [comment]
Doesn't help with the CodeQL warnings. Yes, it's only a warning, but I'd want to reduce amount of spam to make sure important ones won't go unnoticed among it.

**Comment by andreasrosdalw** [comment]
CodeQL is incorrect in this case, it isn't aware of Closure compiler. Can you mark this case as false positive by CodeQL? I don't think it's a good idea to do this change to all global variables. Here the automated checks by CodeQL don't understand Closure compiler.

**Pull request closed without merging**
