### PR TITLE
Unzip mysql-connector with -o

### PR DESCRIPTION
**Pull request by jacobrask**
Fixes crash when trying to reinstall after a previously failed install.

### CODE REVIEW

**Comment by ghost** [comment]
Jacob , thanks for this contribution to Freeciv-web. I hope that you want to submit more improvements to the project!

**Comment by ghost** [comment]
Just wondering, did you get Freeciv-web working in the end? Feel free to ask me any questions if you need any help. Good luck!

**Comment by jacobrask** [comment]
I did! 

I am a web and mobile developer with some design experience, and I
hope to do some improvements of the mobile experience as well as
improve the quality of the JavaScript code base in general if that
will be accepted 😊
Excellent receivement as a first time contributor, thanks 👍


On Sat, May 27, 2017, at 07:18 AM, Andreas Røsdal wrote:
> Just wondering, did you get Freeciv-web working in the end? Feel free
> to ask me any questions if you need any help. Good luck!> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/freeciv/freeciv-web/pull/72#issuecomment-304428673

**Comment by ghost** [comment]
Yes, improvements to the mobile experience, and general quality improvements are very welcome!

**Pull request merged**
